# Generated by Django 3.0.5 on 2020-04-12 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemresolution',
            name='date_0',
            field=models.DateField(default=datetime.date(2020, 4, 12), verbose_name='Date'),
        ),
    ]
