# Generated by Django 3.0.5 on 2020-04-19 23:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200412_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemresolution',
            name='language_code',
            field=models.CharField(default='Python', max_length=10, verbose_name='Language code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problem',
            name='acceptance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='url',
            field=models.URLField(blank=True, max_length=80, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='problemresolution',
            name='big_oh',
            field=models.CharField(choices=[('constant', 'C'), ('logarithmic', 'log'), ('linear', 'N'), ('logarithmicN', 'logN'), ('quadratic', 'N^2'), ('cubic', 'N^3')], max_length=20, verbose_name='Time complexity(big-oh)'),
        ),
        migrations.AlterField(
            model_name='problemresolution',
            name='date_0',
            field=models.DateField(default=datetime.date(2020, 4, 19), verbose_name='Date'),
        ),
    ]
