# Generated by Django 3.0.5 on 2020-04-19 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200419_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='resolution',
        ),
        migrations.AddField(
            model_name='problemresolution',
            name='problem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Problem'),
        ),
    ]
